### ISSUE TITLE
Need release of v6.2.0

### ISSUE THREAD

**Issue by shirshendubhowmick** [davidtheclark/react-aria-menubutton#103]
@davidtheclark Need to release version `6.2.0`, change log updated. Also need to update the demo.

**Comment by ekilah** [comment]
bumping as someone who is eager to grab that React lifecycle update! 👋

**Comment by davidtheclark** [comment]
Published. Thanks for your patience: I was on vacation. I'll set @shirshendubhowmick as an npm collaborator now so you can publish as needed.
