### ISSUE TITLE
Read-only menu items

### ISSUE THREAD

**Issue by spee** [davidtheclark/react-aria-menubutton#136]
It would be great if we could add a read-only menu item, for example to show a status, version number, or other static info. A read-only menu item should not be selectable and it should not close the menu when the user clicks or presses enter on it.

The existing `readOnly` prop might be used for this functionality. The `disabled` prop could work too, but it doesn't cover the purpose as nicely. Currently, these props simply get passed on to the rendered `span`, where they don't have any effect on the behavior of the menu item.

**Comment by shirshendubhowmick** [comment]
Can you acheive this with the `tag` prop ?

Mentioned here ?
https://gitlab.com/smallcase/frontend/smallcase_platform/-/merge_requests/1186

**Comment by shirshendubhowmick** [comment]
Please create a new issue, if problem persists.

**Comment by spee** [comment]
Wasn't a problem as much as a feature request, which is unanswered I believe. Correct me if I'm wrong but the tag name of the menu item has no influence on the selection behavior of the menu.

**Comment by shirshendubhowmick** [comment]
Not really.

As you mentioned it can be solved with `disabled` and `readOnly` prop but those are not applicable to `span` but you can change the tag to something else and try using using those props.

For example you change it a `div` and add some property on it if disabled or readonly based on those you can add codnitional `classNames`to make it look like disbaled and on selection you can check for those properties and handle it accordingly

For example

```JavaScript
this.props.options.map(val => (
      <MenuItem
        className={`menu-item ${val.readOnly ? 'read-only' : ''}`}
        key={val} tag="div"
        data-readonly={val.readOnly}
       >
        {val.label}
      </MenuItem>
)
```

Or maybe you can create your own component and use it in place of `val.label`.

Let me know if this solves your use case.

**Comment by shirshendubhowmick** [comment]
You can have a look into this also 

https://github.com/davidtheclark/react-aria-menubutton/issues/67

**Comment by spee** [comment]
Thanks for you sample @shirshendubhowmick.  I understand I could check if a selected item should be handled, but my idea about supporting read-only items would be that the library checks this before calling the selection handler in the first place. It would also eliminate these items from the focus cycle.

In fact, as #67 shows, including an element other than a `MenuItem` results in this exact behavior (y)

**Comment by shirshendubhowmick** [comment]
I agree there should be a disabled option natively supported by the library. However can't promise a specific date when we will be able to implement that. Currently there are lot a of things going on to improve in the library related to the legacy code.

I have added this feature to the product roadmap https://github.com/davidtheclark/react-aria-menubutton/projects/1

Hopefully will be implemented in sometime.
