### ISSUE TITLE
Add React v17 compatibility

### ISSUE THREAD

**Issue by comatory** [davidtheclark/react-aria-menubutton#140]
`react-aria-menubutton@7.0.0 requires a peer of react@^16.3.0 but none is installed. You must install peer dependencies yourself.`

It's reporting that it's incompatible with React 17.

**Comment by shirshendubhowmick** [comment]
Will fix it soon

**Comment by bdsvc-github** [comment]
Deployment starting to ephemeral!

**Comment by bdsvc-github** [comment]
Deployed to ephemeral!

**Comment by shirshendubhowmick** [comment]
Fixed with v7.0.1
