### ISSUE TITLE
onSelection does not update 

### ISSUE THREAD

**Issue by ajkovar** [davidtheclark/react-aria-menubutton#142]
onSelection is being fed into the manager object on init:

https://github.com/davidtheclark/react-aria-menubutton/blob/master/src/Wrapper.js#L26

If this prop later changes, it does not update in the component.

**Comment by purplecandle** [comment]
For a while, I decided to force-update a whole select component via key prop, which takes a variable that make the onSelect different

**Comment by ekilah** [comment]
This just bit me and it was a tricky bug to narrow down! Props should never be saved like this in React in a constructor without being updated in lifecycle methods like `componentDidUpdate` or `getDerivedStateFromProps`

**Comment by ekilah** [comment]
Added a fix for this in #151
