### ISSUE TITLE
CSSTransitionGroup API thought

### ISSUE THREAD

**Issue by jjt** [davidtheclark/react-aria-menubutton#19]
The current way of passing `CSSTransitionGroup` is uncommon, but it works just fine and assumes nothing about the state of the world outside of the module, which is a good thing.

For a simpler API, you could make `options.transition` a boolean once facebook/react#3785 is in a release version. For global consumers, you would reference `React.addons.CSSTransitionGroup`. For module consumers, just import `CSSTransitionGroup`.

Great writeup and great component btw.

**Comment by davidtheclark** [comment]
Thanks. I'll leave this open as a reminder until that release.

**Comment by davidtheclark** [comment]
With v0.7.0 the `Menu` component can take a function as a child. This allows you to use `ReactCSSTransitionGroup` or any other animation component easily. Hopefully the examples illustrate this sufficiently ... let me know if they don't.
