### ISSUE TITLE
ctrl+r doesn't reload the page when the menu is open

### ISSUE THREAD

**Issue by esseb** [davidtheclark/react-aria-menubutton#24]
Steps to reproduce:
1. Open http://davidtheclark.github.io/react-aria-menubutton/demo/
2. Click the first menu button to open it
3. Press ctrl+r to reload the page

Expected result:
The page should reload.

Actual result:
Nothing happens. F5 works, however.

The problem is with https://github.com/davidtheclark/react-aria-menubutton/blob/master/src/Manager.js#L136 which calls event.preventDefault(); if the pressed key code is a latin character.

One fix would be to only call preventDefault() if the pressed key matches the first letter of one of the menu items, but I'd still like ctrl+r to work even if I have the menu item "rome", and then you get into the whole mess of event.ctrlKey and Windows vs Mac keyboards and people using Alt Gr+e to type the character € which could potentially be the first character of a menu item.

€ isn't a latin character, but I'm sure there's a keyboard locale out there where Alt Gr + a key results in a latin character.

Sorry, I don't have a good suggestion on how to fix this robustly. I hate keyboards.

**Comment by davidtheclark** [comment]
Thanks for reporting this!

Would it work if we add logic saying "If the ctrl key or meta key is pressed, ignore this letter key"? So if you press `r` you'll go to `rain`, but `ctrl+r` or `meta+r` will refresh. Can you see any objection to that?

(As for the alt+key stuff and alternate languages — I'm just going to hope that when somebody does run into that problem they have some idea what behavior is expected and how it might be fixed.)

**Comment by esseb** [comment]
Yeah, your first suggestion would work fine, I agree that the alt gr key stuff can wait until it becomes a practical issue.

**Comment by davidtheclark** [comment]
As soon as the tests pass (Travis seems to be slow), I'll release 2.0.0 with this change.

**Comment by davidtheclark** [comment]
Published.
