### ISSUE TITLE
Remove tap.js dependency

### ISSUE THREAD

**Issue by davidtheclark** [davidtheclark/react-aria-menubutton#33]
The library is no longer maintained: https://github.com/alexgibson/tap.js/

The reason it's being used here is to differentiate between touch clicks and touch scrolls when determining whether there was a click outside the menu (and so it should close).

I don't know of any other libraries that do this well. They all either

- A. use the `touchstart` event, which means that any scroll will close the menu, which means that if the menu is long and scrolling is required the user can only scroll from inside the menu, not outside; or
- B. use a underlay element that detects clicks, which was the initial approach of this library but I dropped it because it meant that any clicks outside the menu were *cancelled*: if you click a button outside the open menu, you have to click it twice for it to work.

So the last option that I know of is:

- C. create a `on-click-outside` module that detects clicks outside of elements using the logic from tap.js, and make that a dependency of this module.

I am not inclined to go for B. So C would work but its another module to maintain (I'm not sure I have the means to test it super well) and it's more code. A might work if nobody cares about its downside.

Any input appreciated.

**Comment by VinSpee** [comment]
I have had success with https://github.com/boblauer/react-onclickout - you might consider using it or a similar approach

**Comment by davidtheclark** [comment]
It doesn't look like that library would support touchscreens. Does it?

**Comment by VinSpee** [comment]
you are correct, it does not. Sorry!

**Comment by davidtheclark** [comment]
Replaced with https://github.com/davidtheclark/teeny-tap
