### ISSUE TITLE
define react & react-dom as peerDependency

### ISSUE THREAD

**Issue by smiLLe** [davidtheclark/react-aria-menubutton#39]
Hey,

i run into the same [issue described here](http://stackoverflow.com/questions/33157904/how-to-avoid-loaded-two-copies-of-react-error-when-developing-an-external-comp).

The result is, i have two different ReactDOM versions. 

I forked your repo, changed the dep in package.json to peerDep and the issues are gone.

**Comment by davidtheclark** [comment]
Seems good and looking around at some other React libraries I see it's common practice.

Do you think this can just be a patch release? That's what I'm thinking.

**Comment by smiLLe** [comment]
Looks good to me. 

Btw. great Lib ! :)

**Comment by davidtheclark** [comment]
Released in 4.0.2.

**Comment by davidtheclark** [comment]
Thanks, @smiLLe!

**Comment by smiLLe** [comment]
Great! Thank you!
