### ISSUE TITLE
separate out the Menu component

### ISSUE THREAD

**Issue by rygine** [davidtheclark/react-aria-menubutton#42]
i'd like to use the Menu portion of the menu button as an ARIA compliant menu. the functionality is there, but it's tightly coupled with the Wrapper/Button to be visible. It would be nice to render menus outside of the menu button (i.e. context menu or navigation menu).

ideally, this would be a separate component, but a refactored export would also work just fine.

thoughts?

edit: i'm willing to do a PR

**Comment by davidtheclark** [comment]
I think the difficult work for the menu itself is the keyboard interaction, and that is available independently in https://github.com/davidtheclark/focus-group. Can you look into that and see if it covers what you're looking for?

If you do end up building a separate package for a menu component that includes those interactions and also aria roles, we can look into using that here.

**Comment by davidtheclark** [comment]
@rygine I'm going to close this because I think focus-group will do what you need. But if you disagree feel free to reopen.
