### ISSUE TITLE
Group MenuItem under a header

### ISSUE THREAD

**Issue by Dude92** [davidtheclark/react-aria-menubutton#43]
Hi,

Is there a way (currently) to group some items under a header (div).
I have some troubles with this workflow, as a click on the header closes the menu even though closeOnSelection is set to false.

Thanks for your help

**Comment by davidtheclark** [comment]
How about this:

```js
<Menu>
  <div>my header </div>
  <ul>
    <li><MenuItem>..</MenuItem></li>
    <li><MenuItem>..</MenuItem></li>
    <li><MenuItem>..</MenuItem></li>
  </ul>
</Menu>
```

**Comment by Dude92** [comment]
Hi David,

Thanks for your quick reply. I tried your example, but as soon as I click on "my header", the menu is closed (but i want this menu to stay)
Do you have the same behavior or am i missing something obvious?

**Comment by davidtheclark** [comment]
Your header div is inside the Menu component?

https://github.com/davidtheclark/react-aria-menubutton/blob/master/lib/Menu.js#L58 shows the intention that a click/tap inside the Menu component should not close the menu.

**Comment by Dude92** [comment]
Yeah, i'm putting the header div inside the Menu.
I tried with the demo : 
return (
      <Wrapper
        className="MyMenuButton"
        onSelection={this.handleSelection.bind(this)}
        closeOnSelection={false}
      >
        <Button className='MyMenuButton-button'>
          click me
        </Button>
        <Menu className='MyMenuButton-menu'>
          <div> my header </div>
          <ul>{menuItems}</ul>
        </Menu>
      </Wrapper>
    );
And the result is the same. handleTap is invoked if i click on an item, but not i i click on the header. even though the header is inside the menu.

**Comment by davidtheclark** [comment]
The reason this is happening, I think, is the `handleBlur()` function in `createManager`. We *do* want the menu to close if focus is not on the trigger or a menu item. And when you click on the heading, that's what happens: focus moves to the document body (or the heading itself, if it's focusable). But then what would happen if you start hitting up/down arrows?

Open to a PR solving this problem.
