### ISSUE TITLE
global is not defined in UMD build

### ISSUE THREAD

**Issue by souporserious** [davidtheclark/react-aria-menubutton#46]
I'm getting the following error in the UMD build

![image](https://cloud.githubusercontent.com/assets/2762082/16401074/19f4ed58-3c96-11e6-8a0c-5889959d5f8a.png)

![image](https://cloud.githubusercontent.com/assets/2762082/16401067/09a30c1e-3c96-11e6-9491-0bca73b2bae5.png)

I couldn't pull from NPMCDN so I just pulled the repo down and built the UMD file. Is there a better way to do this? We use rails at my work and don't have any kind of module system so I need an old school way of it working on the window. Any help would be greatly appreciated. Love this library, as well as all of your others and would like to use them if I can :)

**Comment by davidtheclark** [comment]
Probably just renaming that to `window` should work. I guess I may have assumed webpack would do that when it creates the UMD build, but that was a silly assumption. PR welcome to fix this — should be straightforward.
