### ISSUE TITLE
Provide `isOpen` via external controls.

### ISSUE THREAD

**Issue by hallister** [davidtheclark/react-aria-menubutton#48]
This would cleanly allow adding classes to the Button when the menu is active.

**Comment by AsaAyers** [comment]
You would also need a callback to handle the menu closing in response to the user pressing escape or clicking outside the menu.

```jsx
<Wrapper isOpen={this.state.isOpen} onChange={(isOpen) => this.setState({ isOpen })}>
```

**Comment by davidtheclark** [comment]
If I'm understand correctly: you're essentially talking about being able to manage open/close state outside this component, right? Sounds like a good idea. Definitely open to a PR.

**Comment by hallister** [comment]
Actually, I'm less interested in managing the state and more interested in the top level component knowing whether the menu is open or not so that the Button class can change based on whether the Menu is open

`<Button className={open ? 'open' : 'closed' />`

This probably needs be done via an `onToggle` handler on the `Menu` component. My initial thought was to just add an `isOpen` call to `externalStateControls`:

```javascript
function isOpen(menuId) {
  var manager = registeredManagers[menuId];
  if (!manager) throw new Error('Cannot open ' + errorCommon);
  return manager.isOpen;
}
```

Which technically works as well, but feels a little more awkward than just doing the callback.

**Comment by davidtheclark** [comment]
Closing in favor of @AsaAyers's suggestion of offering `isOpen` and `onClose` props. These could be part of the next major release.
