### ISSUE TITLE
Clicking an unfocusable element inside of the menu closes it

### ISSUE THREAD

**Issue by taylorcode** [davidtheclark/react-aria-menubutton#62]
If there is any space between or around the menu items, clicking it will result in the menu closing. Also, clicking anything inside of the menu (such as a decorative arrow) will also close the menu.

<img width="440" alt="screen shot 2017-04-17 at 3 54 43 pm" src="https://cloud.githubusercontent.com/assets/6465562/25406577/fe9bf272-29bb-11e7-9f19-4e206160e6ee.png">

This is because of this logic. When a menu item is blurred, the menu will close unless there is a newly focused element inside of the menu.

https://github.com/davidtheclark/react-aria-menubutton/blob/master/src/createManager.js#L106
```
function handleBlur() {
  const self = this;
  self.blurTimer = setTimeout(function() {
    const buttonNode = ReactDOM.findDOMNode(self.button);
    const menuNode = ReactDOM.findDOMNode(self.menu);
    const activeEl = buttonNode.ownerDocument.activeElement;
    if (buttonNode && activeEl === buttonNode) return;
    if (menuNode && menuNode.contains(activeEl)) return;
    if (self.isOpen) self.closeMenu({ focusButton: false });
  }, 0);
}
```

One solution is to listen for click events on document in createManager.js, and save a reference to the target as `lastClickedElement`. Then inside of this blur handler, we could check if the `lastClickedElement` is inside of the menu.

**Comment by davidtheclark** [comment]
Makes sense! PR welcome.

**Comment by vnglst** [comment]
Seems like a small issue but I noticed this in my menus as well. A PR would be very welcome! ;-)

**Comment by taylorcode** [comment]
I will PR this change, thank you!

**Comment by vnglst** [comment]
Maybe fixing this will also fix #64?

**Comment by gouegd** [comment]
Great detailed explanation, thank you !
I believe there is an issue though: with this change, once the `handleBlur` callback has run and the menu has not been closed (because the `lastClickedElement` was inside the menu), we won't get further `handleBlur` callbacks, so the menu will just stay open on further actions (even when it should close).

Instead, maybe we could listen to *any* click event, decide if it should close the menu (when the click was not in an element in the menu), and remove that event listener when the menu closes. This doesn't feel great but I don't see a better solution at the moment.

Does it all make sense ? :)

**Comment by davidtheclark** [comment]
> Instead, maybe we could listen to any click event, decide if it should close the menu (when the click was not in an element in the menu), and remove that event listener when the menu closes. This doesn't feel great but I don't see a better solution at the moment.

That seems just fine to me. Event delegation!

Another problem to consider in this issue: where does focus go when you click inside the menu but not on an item? To the menu itself?

**Comment by gouegd** [comment]
> Another problem to consider in this issue: where does focus go when you click inside the menu but not on an item? To the menu itself?

Tentative answer: it goes back where is was, unless the newly focused item is an input/select/textarea. That would allow having a text input to filter the visible items, on top of the items list, in the menu.

**Comment by davidtheclark** [comment]
5.0.2 contains a fix for this. The best I was able to do was get the first menu item to focus if you clicked inside the menu but not on a menuitem or focusable thing.
