### ISSUE TITLE
does onSelection need to be a required prop?

### ISSUE THREAD

**Issue by taylorcode** [davidtheclark/react-aria-menubutton#63]
Can we make onSelection an optional prop?

Although probably a misuse, this library is also nice for creating popovers without menu items. In popovers there are no items to click, so onSelection is not used.

**Comment by davidtheclark** [comment]
> this library is also nice for creating popovers without menu items

Why is that, @taylorcode? What does it provide for this use-case that you like?

**Comment by taylorcode** [comment]
The functionality of a popover (for my use case) is a subset of a menu, so I can use this library for both components. For my popover component, I just pass an noop to onSelection.

I am wondering, is the onSelection prop required to promote proper use of this library for creating menus with menu items?

**Comment by davidtheclark** [comment]
> The functionality of a popover (for my use case) is a subset of a menu

**Comment by davidtheclark** [comment]
> The functionality of a popover (for my use case) is a subset of a menu

I don't think this is the case for most people, especially if you consider the accessibility elements of these different features (different `aria-` attributes, for example). I don't think this module provides the key features of a good modal (e.g. accessibility attributes, focus trap, displacement, scrollbar-hiding adjustments). I did make a module that does, though! https://github.com/davidtheclark/react-aria-modal So I really suggest using a different component for modals.
