### ISSUE TITLE
Console error when 'destroying' menu in simple demo

### ISSUE THREAD

**Issue by vnglst** [davidtheclark/react-aria-menubutton#64]
When destroying the menu in the simple demo using the iPhone 'simulator' from Chrome DevTools the console logs the following error: 

> Uncaught TypeError: Cannot read property 'ownerDocument' of null
>     at demo-bundle.js:21770

This also sometimes happens using the normal desktop mode, but I haven't been able to reproduce that (might be a timing issue with setState?).

To reproduce:
- open demo page
- open devtools, switch to e.g. iPhone5
- destroy menu (last option)

See screenshot below:

![schermafdruk 2017-05-01 17 29 02](https://cloud.githubusercontent.com/assets/3457693/25583902/1c936e18-2e94-11e7-8a99-51fb826b876b.png)

**Comment by davidtheclark** [comment]
Thanks for the report, @vnglst.
