### ISSUE TITLE
onMenuToggle callback causes menu reset

### ISSUE THREAD

**Issue by thijskramer** [davidtheclark/react-aria-menubutton#68]
I've got this menu with the following code: 
```javascript
class FilterDropdown extends Component {
  constructor() {
    super();
    this.state = {
      open: false
    };
  }

  render() {
    const { options, value } = this.props;

    return (
      <Wrapper
        onMenuToggle={({ isOpen }) => { this.setState({ isOpen })}}
      >
        <Button>
          {value} {this.state.isOpen ? 'open' : 'closed'}
        </Button>
        <Menu>
          <div>
            {options.map(option => <MenuItem key={option}>{option}</MenuItem>)}
          </div>
        </Menu>
      </Wrapper>
    );
  }
}
```

When I open the menu, `onMenuToggle` get called where `isOpen` is saved in the state. This causes re-rendering of the whole `FilterDropdown` component, which closes the menu and resets the component into the 'default' state, except for that the word 'open' is shown in the button. 

I'm not sure if this is a bug. Am I doing something wrong here? What do I have to do to make sure the Menu stays open?

**Comment by davidtheclark** [comment]
@thijskramer: Try using a function child for `<Menu>`: https://github.com/davidtheclark/react-aria-menubutton#menu. If that doesn't work, maybe there's a bug to track down.

**Comment by pushred** [comment]
I'm having the same issue, though in just one instance of the dropdown. I'll try to isolate the issue but wanted to note that trying a function child instead is resulting in 1 call to `true` and 2 for `false`

**Comment by pushred** [comment]
Ahhh, in my case I was rendering react-aria-menubutton into a `<label>` tag. The browser seems to have been triggering a click or change on the menu when clicking within the label. With normal HTML elements only a focus on the control is expected.

Not sure this component was ever intended for use as drop-in replacement for `<select />` but that's what I'm doing! Maybe something to sort out with ARIA, I will try to look further (and open a separate issue if there is one).

**Comment by davidtheclark** [comment]
Closing as stale, possibly resolved.
