### ISSUE TITLE
First item should not focus when menu is opened with the mouse

### ISSUE THREAD

**Issue by gbishop** [davidtheclark/react-aria-menubutton#69]
Pull request #61  made focusing the first item on open the default. I agree this is a good change for keyboard access but it has an unwanted side effect for mouse users. When the menu is opened with the mouse, the first item is focused and thus highlighted. This results in an unexpected dual highlight when the mouse user hovers over other menu items. You can see the effect in the basic demo as shown in the screenshot below. This is the result of simply opening the menu with the mouse and then sliding the mouse down a few items.

I think the fix is to inhibit focusing the first item in the Button class when opened with the mouse. Changing this [line](https://github.com/davidtheclark/react-aria-menubutton/blob/master/src/Button.js#L56) to
`    this.context.ambManager.toggleMenu({}, {focusMenu: false});`
fixes it.

![screenshot 2017-07-25 at 5 08 00 pm](https://user-images.githubusercontent.com/198012/28593944-337dea12-715c-11e7-9a43-5762b6d1b0bd.png)

**Comment by davidtheclark** [comment]
@gbishop: I agree with you. Also, the ARIA guidelines we're trying to follow here only specify that first-item-focus behavior for "Keyboard interactions," not for mouse clicks: https://www.w3.org/TR/wai-aria-practices/#menubutton.

👍

**Comment by davidtheclark** [comment]
Check out release 5.0.2.

**Comment by gbishop** [comment]
Yes. That works fine now. Thanks for the quick fix.
