### ISSUE TITLE
Scrolling menu closes with no value if scrollbar is used

### ISSUE THREAD

**Issue by t22james** [davidtheclark/react-aria-menubutton#71]
On a menubutton with many `MenuItem`'s, I'm setting a max-height and setting `overflow:scroll;` on the `Menu` component. The problem is that on trying to click/drag the scrollbar, it seems to register this is a non-`MenuItem` click, and thus closes the menu entirely (without even returning a value of the `MenuItem` which was 'below' the chrome scrollbar at the point clicked).

Any chance you could limit the closing click listener to only trigger on elements outside (and NOT) the `Menu`? I've tried adding an extra div INSIDE the `Menu`, with the scroll on that, but has same issue... it's a non-`MenuItem` click, so closes the menu...

cheers

**Comment by davidtheclark** [comment]
@t22james: A fix for this was supposed to have shipped with v5.0.1: https://github.com/davidtheclark/react-aria-menubutton/blob/master/CHANGELOG.md#501. If you're still having problems in that branch, could you please create a demo illustrating the problem? PRs welcome for fixes.

**Comment by davidtheclark** [comment]
Closing as stale, possibly resolved.
