### ISSUE TITLE
openMenu() throws error onMouseEnter

### ISSUE THREAD

**Issue by leonfeng** [davidtheclark/react-aria-menubutton#73]
![screen shot 2017-11-05 at 02 49 39](https://user-images.githubusercontent.com/241553/32410258-9372c22a-c1d5-11e7-9997-c0973f319b9d.png)

I'm using `react-aria-menubutton` with Gatsby, and trying to get the menu to open on mouse enter. The above screenshot is what I get when I test out [my code](https://github.com/leonfeng/gatsby-playground/blob/eba88d1c1b0221090d15a81c4e48d060ad3990bf/src/pages/index.js), which is a simplified version of the basic example.

In a word, all I'm doing is calling `openMenu()` in the `Button` component's `onMouseEnter` event handler. I also made sure to give the wrapper an id and pass it to `openMenu()`. Am I missing anything?

### Environment:

- "react-aria-menubutton": "^5.1.0"
- gatsby-cli v1.1.19
- node v8.9.0
- macOS v10.12.6

**Comment by davidtheclark** [comment]
@leonfeng: The error message tries to explain the problem. Have you ensured that all the instructions for which components need to be wrapped in a `Wrapper`?

If not, can you please provide more code showing what you're trying to do (especially the JSX that shows how you've nested components)?

**Comment by davidtheclark** [comment]
Closing as stale, possibly resolved.
