### ISSUE TITLE
Default span with button role instead of button element?

### ISSUE THREAD

**Issue by Siilwyn** [davidtheclark/react-aria-menubutton#76]
:wave: hi there, I'm wondering why does the default `Button` create a `span` with `role="button"` instead of using the `button` element?

**Comment by davidtheclark** [comment]
@Siilwyn: Because I didn't want to put the burden on the user of having to reset `<button>` default styling across browsers, if they weren't already doing that. If you see any problems with the interactions, though, let's sort them out.

**Comment by Siilwyn** [comment]
Hi @davidtheclark understandable, maybe the reason behind this should be put in the readme? I asked because using the `button` element seems more straightforward and idiomatic.

Not seeing any problems but in my use-case it makes sense to use `button` since the website already has CSS reset/normalize styling.

**Comment by davidtheclark** [comment]
@Siilwyn: Sure, open to any PRs improving the documentation.
