### ISSUE TITLE
Button property `disabled` should be assigned to the tag element

### ISSUE THREAD

**Issue by karmats** [davidtheclark/react-aria-menubutton#80]
When setting the `Button` property `disabled` to true only the `aria-disabled` attribute is set. The tag should also set the elements `disabled` property (if it for example is a button).

So that this
```html
<Button disabled={disabled} tag="button">
  <span>My button</span>
</Button>
```
will resolve to this
```html
<button role="button" tabindex="" disabled="true" aria-haspopup="true" aria-expanded="false" aria-disabled="true">
  <span>My button</span>
</button>
```

**Comment by davidtheclark** [comment]
Sure, sounds good. PR welcome.

**Comment by karmats** [comment]
PR created :)
