### ISSUE TITLE
Errors in <StrictMode />

### ISSUE THREAD

**Issue by nhardy** [davidtheclark/react-aria-menubutton#88]
The component lifecycle `componentWillMount` will be deprecated in a future 16.x version of React and removed in React 17. [This blog post](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html) explains more.

The legacy context API will also be removed in React 17, replaced with the [new context API](https://reactjs.org/docs/context.html) introduced in 16.3.

`findDOMNode` is also deprecated. [This blog post](https://reactjs.org/docs/strict-mode.html#warning-about-deprecated-finddomnode-usage) explains more. 

These three APIs currently log errors when rendered in a `<StrictMode />` tree, and are a blocker for React's Concurrent Mode.

**Comment by shirshendubhowmick** [comment]
Use of deprecated lifecycle methods have been removed in `v6.2.0`

@nhardy Would like to send PR for `findDOMNode` and lgeacy context API ?

**Comment by nhardy** [comment]
Happy to take a look if I get some time.

**Comment by shirshendubhowmick** [comment]
Sure let me know.

**Comment by nhardy** [comment]
Going to also take a look at #93 which should remove the dependency on `ReactDOM.findDOMNode()` and close out the remaining issue not already addressed in #110. Unfortunately, `React.forwardRef()` is a backwards-incompatible API and would mean we would need to bump the `peerDependencies` for `react`/`react-dom` to `16.3.0`.
