### ISSUE TITLE
Click events propagate

### ISSUE THREAD

**Issue by zioth** [davidtheclark/react-aria-menubutton#92]
When I click on the menu (either a menu option or empty space section), the menu closes, and the click even propagates to elements underneath the menu. This didn't help:
```
<MenuButton.Wrapper
    onSelection={(val, e) => {e.preventDefault(); e.stopPropagation(); props.onSelect(val);}}
```

**Comment by davidtheclark** [comment]
This is intentional — so if you click a button outside the menu, for example, that one click triggers the button and closes the menu.

**Comment by zioth** [comment]
That makes sense if the menu is the only item on the screen, but often, there will be another element underneath it. You close the menu only to accidentally click a button or a link. And since canceling the event in onSelection() doesn't work, there's no way to avoid this behavior.

If the goal is to close the menu after click, that could easily be done without propagating events. Just call the close function after calling the click function. It would be more correct anyway. This menu mimics the behavior of older versions of MacOS, which close menus even if you click on a disabled item, a separator or empty space. Every modern desktop and mobile OS I've used only closes menus if you click on an actionable item.

If you don't agree with my assessment, would it be possible to add an optional property which cancels events? It would make your component much more useful to me and my company.

**Comment by davidtheclark** [comment]
I guess I disagree with the behavior expectation you describe, @zioth: if I have a menu open on the left side of my screen, and I click a button on the right side, I expect that button click to work — not just close the open menu. If there's a translucent backdrop between an overlay and the main UI (as is usually the case for modals), I expect a click on it to do nothing except close the overlay; but that's almost never the case with menus.

If you'd like to propose an API change that would allow for your use case, @zioth, please do 👍

**Comment by zioth** [comment]
I agree with everything you said. The behavior I was seeing was not those expected behaviors (like closing an overlay when clicking outside the menu). In my case, I would click on a menu option, and a button, which happened to be beneath the menu, would get clicked at the same time.

However, this turned out to be a bug in my code. A transparent element with a higher z-index took the click event. I'm closing this issue as invalid.
