### ISSUE TITLE
Seeking co-maintainers!

### ISSUE THREAD

**Issue by davidtheclark** [davidtheclark/react-aria-menubutton#96]
I've been shifting my focus away from UI development, so don't plan on addressing new issues myself. If you use this library and want to see development continue, you can make that happen by becoming a co-maintainer — with permissions to triage issues, merge PRs, cut releases, etc.

Please comment below if you're interested!

Another possibility is for a dedicated owner to fork this code and create a new package. I'd be happy to link to that library from the README of this one.

**Comment by shirshendubhowmick** [comment]
Interested

**Comment by davidtheclark** [comment]
Great, @shirshendubhowmick. You're a collaborator on the repo now, so feel free to triage and work on issues, PRs, etc.

**Comment by ryhinchey** [comment]
Hi @davidtheclark I've been using this library at work and would be happy to help out on PRs and Issues

**Comment by shirshendubhowmick** [comment]
@davidtheclark Thanks, will take care of the repo from now.

**Comment by ivoreis** [comment]
@shirshendubhowmick any luck addressing open PRs?

**Comment by shirshendubhowmick** [comment]
@ivoreis need some more time, got an accident few weeks back, got leg fractured. Will look into the PRs soon.

**Comment by shirshendubhowmick** [comment]
@davidtheclark How do we npm publish this project ?

**Comment by davidtheclark** [comment]
@shirshendubhowmick Hope your leg heals quickly! Not sure I understand the question — I publish using `npm publish`. I haven't yet added you as an npm collaborator: for now, let me know when a release is ready and I'll publish. After a couple of those I'll add you as a collaborator.

**Comment by shirshendubhowmick** [comment]
@davidtheclark Sure, will let you know
