### ISSUE TITLE
Home/End keys don't appear to work

### ISSUE THREAD

**Issue by ryan-codingintrigue** [davidtheclark/react-aria-menubutton#99]
According to the README, <kbd>Home</kbd> and <kbd>End</kbd> keys should be supported as per the ARIA spec, however in both my implementation and the demo page I cannot get this functionality to work.

Chromium: 75.0.3770.142
OS: Windows 10 1903

**Comment by shirshendubhowmick** [comment]
This was added in version 6.2.0, which is not yet released.
